server:
  port: 8000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  datasource:
    url: jdbc:postgresql://193.191.177.108:15432/
    username: SpringBootService
    password: cQ7yxPAtN6dQnySQ3C
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eu-de.appid.cloud.ibm.com/oauth/v4/37bbf07c-83b5-4962-a23c-1a89bc2e11fe

